---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BookManagement
  labels:
    app: BookManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BookManagement
  template:
    metadata:
      labels:
        app: BookManagement
    spec:
      containers:
        - name: BookManagement
          image: username/BookManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanManagement
  labels:
    app: LoanManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanManagement
  template:
    metadata:
      labels:
        app: LoanManagement
    spec:
      containers:
        - name: LoanManagement
          image: username/LoanManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BookManagement
  labels:
    app: BookManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BookManagement


---


apiVersion: v1
kind: Service
metadata:
  name: LoanManagement
  labels:
    app: LoanManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanManagement

